### ISSUE TITLE
Error: spawn yarn ENOENT

### ISSUE THREAD

**Issue by rodrigojmr** [Fabianopb/create-fullstack-react-app#26]
I get this error when attempting to install with `npx create-fullstack-react-app my-app`. Has not happened with other npx installations

```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'install' ]
}
```

**Comment by Fabianopb** [comment]
Hey @rodrigojmr, it looks to me that you're having some kind of problem with `yarn`?
```
Error: spawn yarn ENOENT
```

**Comment by rodrigojmr** [comment]
I have no problems installing other projects with npx or using yarn. Many of the other examples of this error I find are often in development, , or missing `C:\Windows\system32` in system PATH variables, which I already have. I've only found this issue in trying to install this project.
